const defaults = {
  type: 'armor'
}

const armor = {
  leatherHelm: {
    ...defaults,
    armorType: 'head',
    name: 'Leather Helm',
    description: 'A simple leather helm',
    minArmorRating: 1,
    maxArmorRating: 3,
    minWeight: 1,
    maxWeight: 2,
  },
  ironHelm: {
    ...defaults,
    armorType: 'head',
    name: 'Iron Helm',
    description: 'A simple iron helm',
    minArmorRating: 1,
    maxArmorRating: 5,
    minWeight: 2,
    maxWeight: 3,
  },
  chainHelm: {
    ...defaults,
    armorType: 'head',
    name: 'Chain Helm',
    description: 'A simple chain helm',
    minArmorRating: 2,
    maxArmorRating: 5,
    minWeight: 2,
    maxWeight: 3,
  },
  plateHelm: {
    ...defaults,
    armorType: 'head',
    name: 'Plate Helm',
    description: 'A simple plate helm',
    minArmorRating: 4,
    maxArmorRating: 9,
    minWeight: 4,
    maxWeight: 5,
  },
  clothShirt: {
    ...defaults,
    armorType: 'chest',
    name: 'Cloth Shirt',
    description: 'A normal cloth shirt',
    minArmorRating: 0,
    maxArmorRating: 1,
    minWeight: 0,
    maxWeight: 1,
  },
  leatherArmor: {
    ...defaults,
    armorType: 'chest',
    name: 'Leather Armor',
    description: 'A simple leather armor',
    minArmorRating: 2,
    maxArmorRating: 4,
    minWeight: 2,
    maxWeight: 4,
  },
  ironArmor: {
    ...defaults,
    armorType: 'chest',
    name: 'Iron Armor',
    description: 'A simple iron armor',
    minArmorRating: 3,
    maxArmorRating: 6,
    minWeight: 3,
    maxWeight: 5,
  },
  chainArmor: {
    ...defaults,
    armorType: 'chest',
    name: 'Chain Armor',
    description: 'A simple chain armor',
    minArmorRating: 3,
    maxArmorRating: 6,
    minWeight: 3,
    maxWeight: 5,
  },
  plateArmor: {
    ...defaults,
    armorType: 'chest',
    name: 'Plate Armor',
    description: 'A simple plate armor',
    minArmorRating: 5,
    maxArmorRating: 10,
    minWeight: 5,
    maxWeight: 7,
  },
  clothPants: {
    ...defaults,
    armorType: 'legs',
    name: 'Cloth Pants',
    description: 'A normal cloth pants',
    minArmorRating: 0,
    maxArmorRating: 1,
    minWeight: 0,
    maxWeight: 1,
  },
  leatherPants: {
    ...defaults,
    armorType: 'legs',
    name: 'Leather Pants',
    description: 'A simple leather pants',
    minArmorRating: 1,
    maxArmorRating: 3,
    minWeight: 1,
    maxWeight: 2,
  },
  ironPants: {
    ...defaults,
    armorType: 'legs',
    name: 'Iron Pants',
    description: 'A simple iron pants',
    minArmorRating: 1,
    maxArmorRating: 5,
    minWeight: 2,
    maxWeight: 3,
  },
  chainPants: {
    ...defaults,
    armorType: 'legs',
    name: 'Chain Pants',
    description: 'A simple chain pants',
    minArmorRating: 2,
    maxArmorRating: 5,
    minWeight: 2,
    maxWeight: 3,
  },
  platePants: {
    ...defaults,
    armorType: 'legs',
    name: 'Plate Pants',
    description: 'A simple plate pants',
    minArmorRating: 4,
    maxArmorRating: 9,
    minWeight: 4,
    maxWeight: 5,
  },
  leatherShoes: {
    ...defaults,
    armorType: 'feet',
    name: 'Leather Shoes',
    description: 'Simple leather shoes',
    minArmorRating: 1,
    maxArmorRating: 3,
    minWeight: 1,
    maxWeight: 2,
  },
  leatherBoots: {
    ...defaults,
    armorType: 'feet',
    name: 'Leather Boots',
    description: 'Simple leather boots',
    minArmorRating: 1,
    maxArmorRating: 3,
    minWeight: 1,
    maxWeight: 2,
  },
  ironBoots: {
    ...defaults,
    armorType: 'feet',
    name: 'Iron Boots',
    description: 'Simple iron boots',
    minArmorRating: 1,
    maxArmorRating: 5,
    minWeight: 2,
    maxWeight: 3,
  },
  chainBoots: {
    ...defaults,
    armorType: 'feet',
    name: 'Chain Boots',
    description: 'Simple chain boots',
    minArmorRating: 2,
    maxArmorRating: 5,
    minWeight: 2,
    maxWeight: 3,
  },
  plateBoots: {
    ...defaults,
    armorType: 'feet',
    name: 'Plate Boots',
    description: 'Simple plate boots',
    minArmorRating: 4,
    maxArmorRating: 9,
    minWeight: 4,
    maxWeight: 5,
  },
  leatherGloves: {
    ...defaults,
    armorType: 'hands',
    name: 'Leather Gloves',
    description: 'A simple leather gloves',
    minArmorRating: 1,
    maxArmorRating: 3,
    minWeight: 1,
    maxWeight: 2,
  },
  ironGloves: {
    ...defaults,
    armorType: 'hands',
    name: 'Iron Gloves',
    description: 'A simple iron gloves',
    minArmorRating: 1,
    maxArmorRating: 5,
    minWeight: 2,
    maxWeight: 3,
  },
  silverNecklace: {
    ...defaults,
    armorType: 'neck',
    name: 'Silver Necklace',
    description: 'A simple silver necklace',
    minArmorRating: 0,
    maxArmorRating: 2,
    minWeight: 1,
    maxWeight: 2,
  },
  silverRing: {
    ...defaults,
    armorType: 'ring',
    name: 'Silver Ring',
    description: 'A simple silver ring',
    minArmorRating: 0,
    maxArmorRating: 2,
    minWeight: 1,
    maxWeight: 2,
  },
  leatherBelt: {
    ...defaults,
    armorType: 'belt',
    name: 'Leather Belt',
    description: 'A simple leather belt',
    minArmorRating: 0,
    maxArmorRating: 2,
    minWeight: 1,
    maxWeight: 2,
  },
  leatherCloak: {
    ...defaults,
    armorType: 'cloak',
    name: 'Leather Cloak',
    description: 'A simple leather cloak',
    minArmorRating: 0,
    maxArmorRating: 2,
    minWeight: 1,
    maxWeight: 2,
  },
  woodenShield: {
    ...defaults,
    armorType: 'shield',
    name: 'Wooden Shield',
    description: 'A simple wooden shield',
    minArmorRating: 1,
    maxArmorRating: 3,
    minWeight: 2,
    maxWeight: 3,
  },
  ironShield: {
    ...defaults,
    armorType: 'shield',
    name: 'Iron Shield',
    description: 'A simple iron shield',
    minArmorRating: 2,
    maxArmorRating: 5,
    minWeight: 3,
    maxWeight: 4,
  },
  chainShield: {
    ...defaults,
    armorType: 'shield',
    name: 'Chain Shield',
    description: 'A well-crated iron and wood shield, with chainmail covering the front',
    minArmorRating: 3,
    maxArmorRating: 6,
    minWeight: 4,
    maxWeight: 5,
  },
  plateShield: {
    ...defaults,
    armorType: 'shield',
    name: 'Plate Shield',
    description: 'A simple plate shield',
    minArmorRating: 5,
    maxArmorRating: 10,
    minWeight: 6,
    maxWeight: 8,
  }
}

export default armor